

const esDataGrid = {
    noRowsLabel: 'Sin filas',
  noResultsOverlayLabel: 'Resultados no encontrados',
    toolbarDensity: 'Densidad',
    toolbarDensityLabel: 'Densidad',
    toolbarDensityCompact: 'Compacto',
    toolbarDensityStandard: 'Normal',
    toolbarDensityComfortable: 'Amplio',
    toolbarColumns: 'Columnas',
    toolbarColumnsLabel: 'Seleccionar columna',
    toolbarFilters: 'Filtros',
    toolbarFiltersLabel: 'Mostrar filtros',
    toolbarFiltersTooltipHide: 'Ocultar filtro',
    toolbarFiltersTooltipShow: 'Mostrar filtro',
    toolbarQuickFilterPlaceholder: 'Buscar...',
    toolbarQuickFilterLabel: 'Buscar',
    toolbarQuickFilterDeleteIconLabel: 'Limpiar búsqueda',
    toolbarExport: 'Exportar',
    toolbarExportLabel: 'Exportar',
    toolbarExportCSV: 'Descargar como CSV',
    toolbarExportPrint: 'Imprimir',
    toolbarExportExcel: 'Descragar como Excell',
    columnsManagementSearchTitle: 'Buscar',
    columnsManagementNoColumns: 'Sin columnas',
    columnsManagementShowHideAllText: 'Mostrar/Ocultar Todo',
    columnsManagementReset: 'Reiniciar',
    columnsManagementDeleteIconLabel: 'Limpiar',
    filterPanelAddFilter: 'Agregar filtro',
    filterPanelRemoveAll: 'Eliminar todo',
    filterPanelDeleteIconLabel: 'Borrar',
    filterPanelLogicOperator: 'Operador logico',
    filterPanelOperator: 'Operador',
    filterPanelOperatorAnd: 'Y',
    filterPanelOperatorOr: 'O',
    filterPanelColumns: 'Columnas',
    filterPanelInputLabel: 'Valor',
    filterPanelInputPlaceholder: 'Filtrar valor',
    filterOperatorContains: 'Contiene',
    filterOperatorDoesNotContain: 'No contiene',
    filterOperatorEquals: 'igual',
    filterOperatorDoesNotEqual: 'No es igual',
    filterOperatorStartsWith: 'Empieza con',
    filterOperatorEndsWith: 'Termina con',
    filterOperatorIsEmpty: 'Esta vacio',
    filterOperatorIsNotEmpty: 'No esta vacio',
    filterOperatorIsAnyOf: 'Es cualquiera de',
    columnMenuLabel: 'Menu',
    columnMenuShowColumns: 'Mostrar columnas',
    columnMenuManageColumns: 'Gestionar columnas',
    columnMenuFilter: 'Filtro',
    columnMenuHideColumn: 'Ocultar columna',
    columnMenuUnsort: 'Desordenar',
    columnMenuSortAsc: 'Ordenar Acendente',
    columnMenuSortDesc: 'Ordenar Descendente',


}

export default esDataGrid;