site_name: Pedidos Materias Primas
nav:
    - Introducción: index.md
    - Guía de Instalación: 
        - Django: instalacion/instalacion_Django.md
        - React: instalacion/instalacion_React.md
    - Estructura Backend: 
        - PedidosMP: 
            - __pycache__.py: compras/pedidosMPmd/pycache.md
            - __init__.py: compras/pedidosMPmd/init.md
            - asgi.py: compras/pedidosMPmd/asgi.md
            - settings.py: compras/pedidosMPmd/settings.md
            - urls.py: compras/pedidosMPmd/urls.md
            - wsgi.py: compras/pedidosMPmd/wsgi.md
    
theme: material
markdown_extensions:
  - codehilite
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.inlinehilite
